In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [25]:
import pandas as pd

df = pd.read_csv('car_evaluation.csv', header=None)

col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
df.columns = col_names

In [26]:
df.shape

(1728, 7)

In [27]:
df.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [5]:
df.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'], dtype='object')

In [28]:
for i in df.columns:
    print(df[i].unique())
print(df[35:45])

['vhigh' 'high' 'med' 'low']
['vhigh' 'high' 'med' 'low']
['2' '3' '4' '5more']
['2' '4' 'more']
['small' 'med' 'big']
['low' 'med' 'high']
['unacc' 'acc' 'vgood' 'good']
   buying  maint doors persons lug_boot safety  class
35  vhigh  vhigh     3       2      big   high  unacc
36  vhigh  vhigh     3       4    small    low  unacc
37  vhigh  vhigh     3       4    small    med  unacc
38  vhigh  vhigh     3       4    small   high  unacc
39  vhigh  vhigh     3       4      med    low  unacc
40  vhigh  vhigh     3       4      med    med  unacc
41  vhigh  vhigh     3       4      med   high  unacc
42  vhigh  vhigh     3       4      big    low  unacc
43  vhigh  vhigh     3       4      big    med  unacc
44  vhigh  vhigh     3       4      big   high  unacc


In [29]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
  
df = df.apply(le.fit_transform)

In [30]:
for i in df.columns:
    print(df[i].unique())
print(df[35:45])

[3 0 2 1]
[3 0 2 1]
[0 1 2 3]
[0 1 2]
[2 1 0]
[1 2 0]
[2 0 3 1]
    buying  maint  doors  persons  lug_boot  safety  class
35       3      3      1        0         0       0      2
36       3      3      1        1         2       1      2
37       3      3      1        1         2       2      2
38       3      3      1        1         2       0      2
39       3      3      1        1         1       1      2
40       3      3      1        1         1       2      2
41       3      3      1        1         1       0      2
42       3      3      1        1         0       1      2
43       3      3      1        1         0       2      2
44       3      3      1        1         0       0      2


In [6]:
y = df['class']
y.head()

0    2
1    2
2    2
3    2
4    2
Name: class, dtype: int32

In [7]:
y.shape

(1728,)

In [8]:
df = df.drop(['class'], axis = 1)

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df, y, test_size = 0.25, random_state = 42)

In [10]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(criterion='gini', max_depth=5, random_state=34)

# fit the model
model.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=34)

In [11]:
y_pred = model.predict(x_test)

In [12]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.8611111111111112

In [13]:
import pickle

filename = 'model.pkl'
pickle.dump(model, open(filename, 'wb'))